### PR TITLE
HR Module: Initial Setup and Structure

### PR DESCRIPTION
**Pull request by vishalverma9572**
**Title:**
`HR Module: Initial Setup and Structure`

**Description:**
This pull request adds the initial setup for the HR module, including:

- Created the basic folder structure for the HR module.
- Added sample files and assets as placeholders.
- Set up `index.jsx` for the main entry point of the HR module.
- Linted and formatted the code using Prettier and ESLint.

**Changes:**
- 5 files changed with 19 insertions.
  - `src/Modules/HR/components/sample.txt`
  - `src/Modules/HR/index.jsx`
  - `src/Modules/HR/pages/sample.txt`
  - `src/assets/HR_assets/sample.txt`

**Next Steps:**
- We will Continue implementing actual components and logic for the HR module.

### CODE REVIEW

**Comment by dvjsharma** [comment]
Hi @vishalverma9572. Please squash the commits into one.

CC @Adi8712

**Comment by Adi8712** [comment]
@vishalverma9572 change the branch you're pushing to from main to gad-1

**Comment by Adi8712** [comment]
@vishalverma9572 change the branch you're pushing to from `main` to `gad-1`
I've put some suggestions so please rectify or clarify those
Also please refrain from changing any kind of configs or global files(refer reviews), in case of any suggestions which you feel is necessary inform the project leads before making changes

**Comment by Adi8712** [comment]
@vishalverma9572 change the branch you're pushing to from `main` to `gad-1`
I've put some suggestions so please rectify or clarify those
Also please refrain from changing any kind of configs or global files(refer reviews), in case of any suggestions which you feel is necessary inform the project leads before making changes
    @dvjsharma @ramG-reddy perhaps close the PR

**Pull request closed without merging**
